### ISSUE TITLE
Can't get it working following steps

### ISSUE THREAD

**Issue by valentinocossar** [stevenilsen123/mac-keyboard-behavior-in-windows#14]
Hi @stevenilsen123,

Sorry for this issue, maybe I'm doing something wrong. I'm trying to get it to work following the guide. I correctly swapped alt with ctrl and ctrl with alt, I've updated "PowerToys Run" assignment. I've installed AutoHotKey 1.1 and copied the file inside my document folder, copied the snipped inside, and double-clicked on it. But trying to do "cmd + T", iterates over the application bar (first screenshot attached), and also trying other shortcuts the script is not working (eg. "ctrl + C" opens Teams, second screenshot attached). What am I doing wrong? What kind of information can I give you to try to help debug the issue?

P.S. Old shortcuts with ctrl still working as before.

Thank you,
Valentino

![2023-05-09](https://user-images.githubusercontent.com/4087384/236951866-add7e8c3-869b-4def-af45-42188779d494.png)
![2023-05-09 (1)](https://user-images.githubusercontent.com/4087384/236951877-506df6d8-c835-4c80-a959-fd77ab4c7f37.png)

**Comment by valentinocossar** [comment]
Update: now all shortcuts are working with ALT key instead of CTRL, but not working with CMD key.

**Comment by stevenilsen123** [comment]
You referenced that you have a "CMD" key on your keyboard? Are you using a Mac keyboard? This repo is designed to work with a Windows keyboard, not a Mac keyboard. If you are not using a Mac keyboard, can you please share what type of keyboard or laptop you are using? Also please share a screenshot of your key remapping in PowerToys Keyboard Manager.

**Comment by valentinocossar** [comment]
Hi @stevenilsen123, yes I’m using a Mac keyboard. Is there a way to make this script working also on a Mac keyboard? Thank you!

**Comment by stevenilsen123** [comment]
I'm sorry but this solution is for Windows keyboards not for Mac keyboards. I will update the readme to make that clear, sorry about that.
