### ISSUE TITLE
Consider Using AHK for Ctrl/Alt Remapping Instead of PowerToys

### ISSUE THREAD

**Issue by Kaijun** [stevenilsen123/mac-keyboard-behavior-in-windows#17]
I've noticed that AutoHotkey (AHK) is also capable of remapping the `ctrl` and `alt` keys. This raises the question: is it necessary to rely on PowerToys for this remapping task?

One limitation I've encountered with PowerToys is its inability to exclude the Terminal app from key remapping. In certain scenarios, like when using the Terminal, it's essential to maintain the default behavior of the ctrl and alt keys.

I propose that we explore the possibility of using AHK for remapping, as it offers greater flexibility and can be customized programmatically to accommodate various use cases.

**Comment by stevenilsen123** [comment]
It's not a bad thought, but there are just so many shortcuts that get automatically covered using that swap. What exactly is the shortcut you are having an issue with?

**Comment by lovelock** [comment]
I've run into this problem too. And the thing is that my macOS key mapping is also modified, mainly CapsLock is remapped to Ctrl and vice versa. So when I want to replicate the key mapping of **my** macOS key map things get complicated. I'll try to fix this in my fork.
