### ISSUE TITLE
App and tab switching issue

### ISSUE THREAD

**Issue by Intro1997** [stevenilsen123/mac-keyboard-behavior-in-windows#19]
There is a Tab switching issue in your ahk script.
When you running some games (such as Genshin Impact), ahk and PowerToys will be useless. In this case, when you run game in full screen mode then use alt+tab on keyboard, the following things will happen:
1. In game, Windows receives ALT+TAB, then Windows switches to Tab UI interface
2. When Windows at Tab UI interface, ahk and PowerToys start working, then ALT_UP event will be replaced by CTRL_UP. Finally Windows will keep in Tab switching state.
3. When you pick an app and exit the Tab switching state, your ALT key is still in ALT_DOWN state.

I have no idea about fixing this issue based on your ahk script. Maybe it's a good choice to close Alt swapping in PowerToys?

**Comment by stevenilsen123** [comment]
This is not related to my script. Please see: https://appuals.com/windows-11-freeze-issue-when-alt-tabbing/

**Comment by Intro1997** [comment]
> This is not related to my script. Please see: https://appuals.com/windows-11-freeze-issue-when-alt-tabbing/

I briefly glanced at the article and it mentioned that this "Freeze Issue" manifests itself as "When this is happening, the players are saying that their screen freezes and they can't do anything besides rebooting their computers", which is not The problem I encountered was that Alt-Tabbing did not freeze the system when I did not use your script. The problem I encountered was that when I opened the script, then running Genshin Impact and used Alt-Tabbing, the window for switching applications stopped, but the system was still able to respond to my operation and was not stuck. However, the ALT key at this time did not receive the RELEASE event, causing the process to be interrupted. When inputting other keys, the system always responds to keyboard input in the form of ALT+KEYS key combination.

**Comment by Intro1997** [comment]
This problem seems to be that Genshin Impact's anti-cheat software blocks the key mapping of powertoys and ahk. I will try to find a solution later.

**Comment by Intro1997** [comment]
Opening powertoys and autohotkey with administrator rights can solve this problem.

**Comment by stevenilsen123** [comment]
Interesting. Thank you for sharing!
