### ISSUE TITLE
Cmd + Space

### ISSUE THREAD

**Issue by ennioVisco** [stevenilsen123/mac-keyboard-behavior-in-windows#2]
About this combination I would also add that the power toys have `PowerToys Run` which can be a convenient replacement to Cmd+ Space, as it is already installed if one follows the prerequisites :)

**Comment by stevenilsen123** [comment]
Mind blown. Apparently MS actually used Wox to make PowerToys Run! Will update! Thanks!
![image](https://user-images.githubusercontent.com/26051016/215375792-5b4925e0-3916-48e8-bb81-18473a0179b3.png)

**Comment by stevenilsen123** [comment]
All set! Thanks again!

**Comment by ennioVisco** [comment]
> All set! Thanks again!

Haha thank you, happy to help!!
