### ISSUE TITLE
AHK 2.0 compatibility?

### ISSUE THREAD

**Issue by diegov00** [stevenilsen123/mac-keyboard-behavior-in-windows#3]
AHK 2.0 recently released publicly and is now the only actively developed version of AHK.
Is this script written for AHK 2 or do i still need to run AHK 1.1 in order to use this?

**Comment by stevenilsen123** [comment]
It runs on 1.1 for now, but I'll leave this open until it gets converted to 2.0.

**Comment by stevenilsen123** [comment]
Done!
