### ISSUE TITLE
Win as Cmd

### ISSUE THREAD

**Issue by kristiannotari** [stevenilsen123/mac-keyboard-behavior-in-windows#4]
Sorry for not being an expert on the topic, but would it be possible or "comfortable" to have the Windows Key be the replacement of the Command key on macs, instead of Alt?

That would be more natural, as I use the same keyboard for both a closed shell macbook and my windows pc at home.

If yes, how? 😄 

> - Command = ~Alt~ Windows key
> - Option = ~Windows~ Alt key
> - Control = Ctrl key

**Comment by stevenilsen123** [comment]
The mac keyboard layout has command next to the spacebar, so on Windows keyboards that would be the Alt key.

**Comment by kristiannotari** [comment]
That's true, but I use a windows keyboard both for my MacBook Pro (shell closed) and my windows pc. So the command key is not next to the spacebar, but there's Alt between the two. And on Mac, I use the windows logo key as command key. So it would be natural to use the same key on windows when simulating Mac key mapping

**Comment by stevenilsen123** [comment]
Well, it's not the goal of this project to support this layout, but if you want to do it for yourself, you could map the Windows key to Ctrl and Ctrl to Alt as a starting point.

**Comment by j0hnm4r5** [comment]
IMO it should be the goal of this project to support both Windows and Mac keyboards. There's no alternative right now for Mac keyboards, so why not grab that market?

**Comment by stevenilsen123** [comment]
@kristiannotari is not asking for Mac keyboard support in Windows, he's asking for Windows keyboard support in Mac. Regarding Mac keyboard support on Windows, I would be happy to add another dev to the project that wants to build out support for that. Until that day comes, this project will only support Mac keyboard shortcuts in Windows, using a Windows keyboard.
