### ISSUE TITLE
Cmd + Tab (hold) does not allow to use Left and Right arrow keys 

### ISSUE THREAD

**Issue by odragora** [stevenilsen123/mac-keyboard-behavior-in-windows#6]
When you invoke App Switcher using Cmd + Tab and try to navigate between opened apps using arrow keys, pressing Left or Right arrow key immediately closes the app switcher.

I think it might be a conflict with Cmd + arrow keys config in the script.

**Comment by stevenilsen123** [comment]
This should be fixed. Please confirm
