### ISSUE TITLE
Requires Administrator rights

### ISSUE THREAD

**Issue by pimlottc** [stevenilsen123/mac-keyboard-behavior-in-windows#8]
I'm trying to use this on a work-issued Windows computer which is pretty heavily locked down.  I can run AutoHotKey from my user directory but I don't have Administrator rights and I can't install anything from the Microsoft Store, including PowerToys.

Is there a way to get the same functionality, or at least as much as possible, without needing Administrator rights?  Can the Ctrl-Alt swap be done in AHK instead?

Thanks!

**Comment by stevenilsen123** [comment]
I can't remember why I had the admin rights requirement in the script, but it's not needed so I removed it in the latest release. However, the script is written assuming your Ctrl and Alt keys are swapped, and many of the shortcuts are accomplished purely based on that fact with no code in the script needed at all. That said, some discussion [here](https://stackoverflow.com/questions/18454895/using-auto-hotkey-to-swap-ctrl-alt-and-implement-ctrl-tab) seems to indicate that it's possible to accomplish the Ctrl/Alt swap purely in Autohotkey while still preserving the proper app switching behavior. I don't have time to work on this right now, but I'd be happy to add anyone as a collaborator to this project if they want to take this on.

**Comment by pimlottc** [comment]
Actually, I might have been wrong; the link for Powertoys goes to the Microsoft Store, which I am unable to use.  But it's also [available via Github](https://github.com/microsoft/PowerToys), and I was able to install the User version successfully.  Perhaps the project should link to that one instead.

**Comment by stevenilsen123** [comment]
Nice find! Added note to the readme!
